class AddMultiLngParentIdToModels < ActiveRecord::Migration
  def change
  	add_column :events, :multi_lng_parent_id, :integer
  	add_column :microsites, :multi_lng_parent_id, :integer
  	add_column :speakers, :multi_lng_parent_id, :integer
  	#add_column :event_venues, :multi_lng_parent_id, :integer
  	add_column :invitees, :multi_lng_parent_id, :integer
  	add_column :agendas, :multi_lng_parent_id, :integer
  	add_column :faqs, :multi_lng_parent_id, :integer
  	add_column :qnas, :multi_lng_parent_id, :integer
  	add_column :conversations, :multi_lng_parent_id, :integer
  	add_column :polls, :multi_lng_parent_id, :integer
  	add_column :awards, :multi_lng_parent_id, :integer
  	add_column :sponsors, :multi_lng_parent_id, :integer
  	add_column :feedbacks, :multi_lng_parent_id, :integer
  	add_column :feedback_forms, :multi_lng_parent_id, :integer
  	add_column :images, :multi_lng_parent_id, :integer
  	add_column :panels, :multi_lng_parent_id, :integer
  	add_column :event_features, :multi_lng_parent_id, :integer
  	add_column :e_kits, :multi_lng_parent_id, :integer
  	add_column :contacts, :multi_lng_parent_id, :integer
  	add_column :notifications, :multi_lng_parent_id, :integer
  	add_column :highlight_images, :multi_lng_parent_id, :integer
  	add_column :groupings, :multi_lng_parent_id, :integer
  	add_column :quizzes, :multi_lng_parent_id, :integer
  	add_column :invitee_structures, :multi_lng_parent_id, :integer
  	add_column :exhibitors, :multi_lng_parent_id, :integer
  	add_column :registration_settings, :multi_lng_parent_id, :integer
  	add_column :registrations, :multi_lng_parent_id, :integer
  	add_column :user_registrations, :multi_lng_parent_id, :integer
  	add_column :custom_page1s, :multi_lng_parent_id, :integer
  	add_column :custom_page2s, :multi_lng_parent_id, :integer
  	add_column :custom_page3s, :multi_lng_parent_id, :integer
  	add_column :custom_page4s, :multi_lng_parent_id, :integer
  	add_column :custom_page5s, :multi_lng_parent_id, :integer
  	add_column :chats, :multi_lng_parent_id, :integer
  	add_column :invitee_groups, :multi_lng_parent_id, :integer
  	add_column :my_travels, :multi_lng_parent_id, :integer
  	add_column :telecaller_accessible_columns, :multi_lng_parent_id, :integer
  	#add_column :venue_sections, :multi_lng_parent_id, :integer
  	add_column :agenda_tracks, :multi_lng_parent_id, :integer
  	add_column :manage_invitee_fields, :multi_lng_parent_id, :integer
  	#add_column :my_travel_docs, :multi_lng_parent_id, :integer
  	#add_column :courses, :multi_lng_parent_id, :integer
  	add_column :qna_settings, :multi_lng_parent_id, :integer
  	add_column :registration_look_and_feels, :multi_lng_parent_id, :integer
  	add_column :track_links, :multi_lng_parent_id, :integer
  	add_column :telecaller_groups, :multi_lng_parent_id, :integer
  	add_column :emergency_exits, :multi_lng_parent_id, :integer
  	add_column :qna_walls, :multi_lng_parent_id, :integer
  	add_column :conversation_walls, :multi_lng_parent_id, :integer
  	add_column :poll_walls, :multi_lng_parent_id, :integer
  	add_column :quiz_walls, :multi_lng_parent_id, :integer
  	add_column :badge_pdfs, :multi_lng_parent_id, :integer
  	add_column :smtp_settings, :multi_lng_parent_id, :integer
  	add_column :favorites, :multi_lng_parent_id, :integer
  	add_column :analytics, :multi_lng_parent_id, :integer
  	#add_column :course_providers, :multi_lng_parent_id, :integer
    add_column :winners, :multi_lng_parent_id, :integer
    add_column :my_profiles, :multi_lng_parent_id, :integer
  end
end
