source 'https://rubygems.org'


gem 'rails', '4.2.1'
gem 'mysql2', '~> 0.3.18'
gem 'execjs'
gem 'therubyracer'
gem 'sass-rails', '~> 5.0'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails', '~> 4.1.0'
gem 'jquery-rails'
# gem 'turbolinks'
gem 'jbuilder', '~> 2.0'
gem 'sdoc', '~> 0.4.0', group: :doc
gem 'devise'
gem 'cancancan'
gem 'rolify'
gem 'haml-rails'
gem 'rails-observers'
gem "paperclip", "~> 4.3"
gem 'rmagick'
gem 'ckeditor', github: 'galetahub/ckeditor'
gem 'aws-sdk', '< 2.0'
gem 'exception_notification'
gem 'httparty'
gem 'json'
gem 'aasm'
gem "nested_form"
gem 'gcm'
gem 'acts-as-taggable-on', '~> 3.4'
gem 'will_paginate', '~> 3.0.6'
gem "roo"
gem 'roo-xls'
gem 'to_xls'
gem "jquery-fileupload-rails"
gem 'bcrypt-ruby', :require => 'bcrypt'
gem 'whenever', :require => false
gem 'rqrcode_png'
gem 'vpim'
gem 'ransack'
gem 'rails4-autocomplete'
gem 'jquery-ui-rails'
gem 'activerecord-session_store', github: 'rails/activerecord-session_store'

gem 'select_all-rails'

gem 'newrelic_rpm'
gem 'twitter'
gem 'fcm'

gem 'select_all-rails'
gem 'actionpack-action_caching'
gem 'deep_cloneable', '~> 2.2.2'
gem 'active_model_serializers', "~> 0.8.0"
#gem 'ar-octopus'


# gem "bullet", :group => "development"

group :development, :test do
  gem 'awesome_print'
  gem 'byebug'
  gem 'did_you_mean', '0.10'
  gem 'web-console', '~> 2.0'
  gem 'spring'
  gem "pry"
end


